name: CI
on: [ push, pull_request ]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
            submodules: recursive

      - name: Install dependencies
        run: sudo make deps

      - name: Make all including validation
        run: make all
